### ISSUE TITLE
Non expected export declarations in generated files

### ISSUE THREAD

**Issue by tfactor2** [finom/babel-plugin-transform-es2015-modules-simple-amd#5]
Say, we have a source:

``` javascript
export function func1() {}

export function func2() {}

export default { func1, func2 };
```

Convert the source using the plugin.

**Actual results contain `export` keyword:**

``` javascript
"use strict";

define([], function () {
  export function func1() {}

  export function func2() {}

  return { func1: func1, func2: func2 };
});
```

**Expected results:**

``` javascript
"use strict";

define([], function () {
  function func1() {}

  function func2() {}

  return { func1: func1, func2: func2 };
});
```

**Comment by finom** [comment]
The plugin supports only default exports and I'm not going to support named exports. Also It's not very clear why do you want to export func1 and func2 and then export an object with such keys? Since exported stuff is exported as is (doesn't contain `__esModule` and `default` keys) I cannot see any use cases of repeating these exports as named.

**Comment by tfactor2** [comment]
Indeed.
Seems that named exports are supported by the way.

Source:

``` javascript
import { func1 as f1 } from './actual';
import actual from './actual';

console.log(f1);
console.log(actual);
```

Target:

``` javascript
'use strict';

define(['./actual', './actual'], function (_actual, actual) {
  var f1 = _actual.func1;


  console.log(f1);
  console.log(actual);
});
//# sourceMappingURL=actualR.js.map
```

**Comment by tfactor2** [comment]
>  Also It's not very clear why do you want to export func1 and func2 and then export an object with such keys?
1. It's an ultimate case that is valid from ES6 point of view.
2. Generated by transpiler code must be valid or the transpiling process should fail. Now generated files are invalid from ES5 point of view.
3. Say we have a case where the module is consumed by 3rd party AMD-module but also is used inside the project that is ES6 modules-compatible. Named exports are really useful from static checking point of view. `import { func3 } from './actual'` will be treated as an error by linter (e.g. via "eslint-plugin-import")

**Comment by finom** [comment]
The plugin is not an ideal thing and for me it makes sense as stupid AMD transpiler with default exports (AMD doesn't have things which I can call named exports).

There can be added a lot of features ([like there](https://github.com/finom/babel-plugin-transform-es2015-modules-simple-commonjs)) but your PR doesn't cover any full feature but covers only one weird use case. Also I'm not really interested to maintain this thing by myself because AMD is dying. Sorry, I'm not going to accept your PR. Feel free to fork and publish your own version of the plugin

**Comment by tfactor2** [comment]
Your plugin is awesome and _especially_ if we are talking about migrating from dying AMD to shiny ES6 modules.
Standard babel AMD plugin is useless as it can't provide _soft_ migration from AMD based frameworks (like dojo).
The case that I covered allows to use cool feature as named exports in a new project without touching old libs for transition period of time.
Please reconsider a possibility to merge.
PS: the link you provided redirect to your GitHub project page.

**Comment by finom** [comment]
> Please reconsider a possibility to merge.

Please make your own package. I'm not going to add features anymore.

> PS: the link you provided redirect to your GitHub project page.

Yes, I wanted to say that the project is also created for migrating but all changes made to the plugin are full. Your PR removes named export by declaration node which makes potential bugs for other users (they could want to use named exports but they get nothing instead of syntax error).
